appName: myhelmapp2

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: devopsjourney1/mywebapp
  tag: latest


test:
  default: fallback-default-vaule

INGRESS_HOSTNAME_SUFFIX: cloud.kyriba.com
PLATFORM_INSTANCE_ID: us4-pre-a